### ISSUE TITLE
Protected Build

### ISSUE THREAD

**Issue by Python1320** [thingsee/thingsee-sdk#11]
Hello,

Protected build does not compile out of the box. Some of the Thingsee apps seem to not have been made for this mode. Do you have any future plans for the NuttX protected build mode? http://nuttx.org/doku.php?id=wiki:howtos:kernelbuild

Some of the problems we have faced:
noreturn returns?

```
thingsee-sdk/nuttx/include/unistd.h: In function '_exit':
proxies/PROXY__exit.c:10:1: error: 'noreturn' function does return [-Werror]
 }
 ^
```

errno is being directly set?

```
dns_socket.c: In function 'dns_send_query':
dns_socket.c:407:16: error: lvalue required as left operand of assignment
          errno = EMSGSIZE;
                ^
dns_socket.c:419:20: error: lvalue required as left operand of assignment
              errno = EMSGSIZE;
                    ^
dns_socket.c:435:13: error: lvalue required as left operand of assignment
       errno = EMSGSIZE;
             ^
dns_socket.c:451:13: error: lvalue required as left operand of assignment
       errno = EMSGSIZE;


```

-- Thingsec team

**Comment by Python1320** [comment]
Investigating further.

Memory layout scripts ( Close similarity to tsone https://github.com/ya-mouse/nuttx-boards/tree/master/mikroe-stm32f4/scripts ) and kernel Makefiles ( https://github.com/ya-mouse/nuttx-boards/tree/master/mikroe-stm32f4/kernel ) are also missing, probably to simplify getting the device up and running.

**Comment by jkivilin** [comment]
You're right, Thingsee applications have not been designed for protected build and would need new protected-build enabled APIs to access board-level functions. We do not have plans for protected build at the moment.
