### ISSUE TITLE
NSH over USB

### ISSUE THREAD

**Issue by Python1320** [thingsee/thingsee-sdk#12]
Hello,

Have you tried getting NSH working in the normal retail build? With "nsh" build we lose everything else such as GUI, which is not ideal.

We have managed to merge the configurations from nsh and retail to keep retail functionality and try to bring nsh to usb by removing storage mode: https://github.com/Python1320/capstone_project/blob/master/config_nsh_gui_narcoleptic

Current problems we are trying to fix:
- you need to connect the device to pc after it has booted or the connection does not work
- you need to keep the device screen on or the connection cuts and you need to reboot the device (Deep sleep issue with the ts_engine apparently)

Ideally the NuttX composite USB mode could be used to get both usb storage and nsh terminal working together, but we haven't managed to get this working yet either.

-- Thingsec team

**Comment by Python1320** [comment]
We finally got the USB serial to work in retail mode with the following config flags after we discovered them:

```
CONFIG_BOARD_INITIALIZE_USB_SERIAL=y
CONFIG_BOARD_RND_USE_USB_CONSOLE=y
```

No NSH, though and going to sleep (screen turning off) still disconnects and coming out of sleep enables storage mode only, requiring reboot. 

For sleep issues our current easiest workaround is going to settings menu to prevent sleeping.

**Comment by jkivilin** [comment]
Enabling following config flags in retail mode should enable NSH on USB:

```
CONFIG_BOARD_DISABLE_DEEPSLEEP=y
CONFIG_BOARD_INITIALIZE_USB_SERIAL=y
CONFIG_NSH_USBCONDEV="/dev/ttyACM0"
CONFIG_NSH_USBCONDEV_ARCHINIT=y
CONFIG_NSH_USBCONSOLE=y
CONFIG_USBDEV_MINOR=0
```

**Comment by Python1320** [comment]
Confirmed working.
